#!/usr/bin/env python
"""
Quinn Perfetto 2015

Quick copying of files to the clipboard

If you have ever used vim or any other command line text editor, you know how hard
it is to copy an entire file to the clipboard

Usage:

cb <filename>

"""

import sys, os, pytools

pytools.assert_n_args(1, "Usage: cb <filename>")
pytools.error_if(not os.path.exists(sys.argv[1]),
        "Invalid file")
os.system("cat " + sys.argv[1] + " | pbcopy")
