#!/usr/bin/env python

'''
Quinn Perfetto 2015

Port state checking using python-nmap

*** DO NOT USE THIS PROGRAM WITHOUT EXPLICIT CONSENT FROM THE HOST.
I DO NOT CONDONE THE USE OF THIS PROGRAM WITHOUT PERMISSION ***

Usage:

checkport <address>:<port>[-<endport>]

Again, I really dont condone using this for anything other than checking your own security

'''
import nmap
import pytools
import sys

def port_scan(host,port): #checks the state of a given port on the host computer
	nm = nmap.PortScanner()
	nm.scan(host,port)
	state = nm[host]['tcp'][int(port)]['state']
	print "[*] " + host + " tcp/" + port + ": " + state

def main():
        usage = "Usage: checkport <address>:<port>[-<endport>]"
        pytools.assert_n_args(1, usage)
        (host, port) = tuple(sys.argv[1].split(":"))

        if "-" in port:
            (start, end) = tuple(port.split("-"))
            for i in range(int(start), int(end) + 1):
                # nmap likes the ports as strings
                port_scan(host, str(i))
        else:
            port_scan(host, port)

if __name__=="__main__":
	main()
