#!/usr/bin/env python

'''
Quinn Perfetto 2014


Image file exif data analyzer


Usage:

imageanalyze -f <image file>

The output on this one can get long and wonky so I would reccomend redirecting it to a text file

e.x. imageanalyze -f <image file> > exif.txt

'''


from ExifTags import TAGS
import optparse
import Image


def testForExif(imgFileName):
	try:
		imgFile=Image.open(imgFileName)
		info=imgFile._getexif()
		if len(info)>0:
			print "[*] Exif data for "+imgFileName
			for (tag, value) in info.items(): 
				decoded = TAGS.get(tag, tag) 
				print str(decoded)+":\t"+str(value)+"\n"

		else:
			print "[-] No metadata found for "+imgFileName

	except:
		pass



def main():
	parser=optparse.OptionParser("Usage imageanalyze -f <image file>")
	parser.add_option("-f",dest="filename",type="string",help="Specify an image file")
	(options,args)=parser.parse_args()
	filename=options.filename

	if filename==None:
		print parser.usage
		exit(0)

	testForExif(filename)



if __name__=="__main__":
	main()

