#!/usr/bin/env python


'''
Quinn Perfetto 2015

IP Location using the pygeoip module

Usage:

iplocate <IP Address>

Where <IP Address> is a valid public IP address and <filename> is a file which contains a list of valid public IP Addresses separated
by newline characters

'''

import pygeoip
import optparse
import os
import sys
import pytools

path = os.path.dirname(os.path.realpath(__file__))+"/"
# The database that will be giving us the location information
gi = pygeoip.GeoIP(path+'resources/GeoLiteCity.dat')

def find_location(target):
    try:
        # Get the record from the geoip database
        record = gi.record_by_name(target)
        city = record['city'] # Grab the information
        region = record['region_code']
        country = record['country_name']
        long = record['longitude']
        lat = record['latitude']
        print "[*] " + target + " Located"
        print "[+] " + str(city) + " " + str(region) + " " + str(country)
        print "[+] Latitude: " + str(lat) + " Longitude: " + str(long)
    except:
        print "Invalid IP Address"


def main():
    pytools.assert_n_args(1, "Usage: iplocate <IP Address>")
    find_location(sys.argv[1])

if __name__=="__main__":
	main()
