#!/usr/bin/env python

"""
Quinn Perfetto 2015

Given a list of file extensions, this counts the number of lines of code
in a recursive search of the current directory for each extension type,
as well as the sum of all of them

Usage:
    lines extension[ extension]*

"""


import os
import sys

if len(sys.argv) == 1:
    print "Usage: lines extension[ extension]*"
    exit(0)

exts = sys.argv[1:]

total = 0
for exten in exts:
    msg = os.popen('find . "(" -name "*.' + exten + '" ")" -print0 | xargs -0 wc -l | grep total').read()
    n_lines = int(msg.split()[0])
    print "{0:10s} : {1:10d} lines".format(exten, n_lines).ljust(20)
    total += n_lines
print "-" * 30
print "{0:10s} : {1:10d} lines".format("Total", total)



