#!/usr/bin/env python

'''
Quinn Perfetto 2015

PDF Metadata analysis using pyPdf

Usage:
pdfanalyze <PDF file>
'''

import pyPdf
import optparse
from pyPdf import PdfFileReader
import pytools
import sys

def print_meta(filename): #Read and display the PDF meta data
	try:
		pdf_file = PdfFileReader(file(filename, 'rb')) #open the file
	except:
		print "Invalid input file"
		exit(0)

	doc_info = pdf_file.getDocumentInfo() #get the info
	print '[*] PDF MetaData For: ' + str(filename)
	for meta_item in doc_info:
		print '[+] ' + meta_item + ':' + doc_info[meta_item]

def main():
    pytools.assert_n_args(1, "Usage: pdfanalyze <filename>")
    print_meta(sys.argv[1])

if __name__=="__main__":
	main()
