#!/usr/bin/env python

'''
Quinn Perfetto 2014


PDF Metadata analysis using pyPdf


Usage:

pdfanalyze -f <PDF file>


'''


import pyPdf
import optparse
from pyPdf import PdfFileReader


def printMeta(filename): #Read and display the PDF meta data
	try:
		pdfFile = PdfFileReader(file(filename, 'rb')) #open the file
	except:
		print "Invalid input file"
		exit(0)

	docInfo = pdfFile.getDocumentInfo() #get the info

	print '[*] PDF MetaData For: ' + str(filename)

	for metaItem in docInfo:
		print '[+] ' + metaItem + ':' + docInfo[metaItem] #display the info


def main():
	parser = optparse.OptionParser('Usage pdfanalyze -f <PDF file name>')
	parser.add_option('-f', dest='filename', type='string',help='specify PDF file name')
	(options, args) = parser.parse_args()
	filename=options.filename

	if filename==None:
		print parser.usage
		exit(0)

	else:
		printMeta(filename)



if __name__=="__main__":
	main()