#!/usr/bin/env python

'''
Quinn Perfetto 2014

Gives information on the primality of numbers
I found myself googling about this alot, and figured i would make it faster

This may be adapted in the future to analyze the number further
'''

import sys
import math

def factors(n):
	f = []
	for i in xrange(1, int(math.sqrt(n)) + 1):
		if n % i == 0:
			f.append((i, n/i))
	return f

def main():
	if len(sys.argv) == 1:
		print "Usage: prime <number>"
		exit(0)
	n = int(sys.argv[1])
	f = factors(n)
	if len(f) == 1:
		print str(n) + " is prime"
	else:
		print "the factors of " + str(n) + " are:"
		print f

if __name__ == "__main__":
	main()
